### PR TITLE
Add AppCompat styles to default styles

### PR DESCRIPTION
**Pull request by paul-turner**
Fixes the issue highlighted at the end of #130

### CODE REVIEW

**Comment by paul-turner** [comment]
Only concern is that `android.R.attr.checkedTextViewStyle` is a API 17 attr, but should compile fine since it is a constant as long as your `compileSdkVersion` is higher correct?

**Comment by chrisjenx** [comment]
The attribute will compile. But as those classes can be accessed during lookup, If you didn't have the v7 lib, it will crash.

**Comment by chrisjenx** [comment]
What it should really do is do a reflective lookup on start and add it to the default map if it can find the `v7` stuff on the classpath (See how it does it with the toolbar check).

**Comment by paul-turner** [comment]
Will do, just saw the toolbar check as well. Thanks!

**Comment by paul-turner** [comment]
Do you think I should:
- check each individual widget before adding it to the map
- look for one of the specific `AppCompatTextView` and assume the rest are there
- piggy-back off the `Toolbar` class check and assume the rest are there because they are contained within AppCompat

Not sure if I'm over thinking it and should just go with the last option and rename the method to be a more general AppCompat check (while still looking for just `Toolbar`).

**Comment by chrisjenx** [comment]
I would check for one of the `AppCompat*` classes, probably `AppCompatTextView` as it would be a _fairly_ safe assumption that the rest are there.
I can't remember if they were added at the same time, but I think `AppCompat*` were added after the Toolbar?

**Comment by paul-turner** [comment]
Should be good to go now.

**Comment by chrisjenx** [comment]
Cool, much better, I would do the lookup inside the static method (for the cases where you might create multiple configs):
```
static {
 DEFAULTMAP.add....
 if (CalligraphyUtils.canAddV7AppCompatViews()) {
            addAppCompatViews(tempMap);//etc...
        }
}
``

**Comment by paul-turner** [comment]
Switched over into the static initialization.

**Comment by chrisjenx** [comment]
Just pushed a 2.1.1 snapshot with this.

**Pull request merged**
