### PR TITLE
Save a few int[] allocations

### LINKED ISSUE #230: CalligraphyUtils should cache attributeId int[] arrays
For a view with about 22 TextViews, Calligraphy will create about 22 `int[]` arrays like so:
screen shot 2015-12-09 at 12 02 57

This seems excessive, especially as the arrays are ALWAYS containing the same value (`attributeId`). 

Could this be replaced by a simple `LruCache`?

I'm trying to reduce allocations within my app to increase scroll and GC performance, this might contribute a little bit.

The other question is why `CalligraphyFactory` and `CalligraphyLayoutInflater` aren't kept based on the Context but re-allocated. There is really no need to re-create them.

### PR DESCRIPTION
**Pull request by ened**
Save a few int[] object allocations. 

Fixes #230.

### CODE REVIEW

**Comment by chrisjenx** [comment]
OK, without any measured performance on allocations vs overhead of method execution and binary search of the SparseArray its hard to say if this is actually better, agreed we would stop allocating memory each time, but that is probably less of hit over what I just mentioned.

But you are right this can be improved and I will come back with some suggestions.

`new int[]{android.R.attr.textAppearance}` can be `static final`.

Also the `attributeId` is derived from the `CalligraphyConfig.Builder` so. A better use would actually be creating `new int[]{attributeId}` when constructing the `CalligraphyConfig` and passing that into the method:

```java
static String pullFontPathFromStyle(Context context, AttributeSet attrs, int[] attributeIdArray) {
}
```

The other stuff you would need to prove the additional overhead of virtual method calls outweighs some very small allocations.

**Comment by ened** [comment]
@chrisjenx: 

- `static final int[]` for `android.R.attr.textAppearance` 
- `pullFontPathFromStyle` with `int[]` array

Will you modify or should I update this PR?

**Comment by chrisjenx** [comment]
If you can update the PR that would be great. I would drop the sparse array
though. We can look at better ways of improving efficiency with the styles
and textAppearance later after measuring.

Thanks.

**Comment by ened** [comment]
@chrisjenx Ready for review.

**Comment by chrisjenx** [comment]
Cool, looks good. Thanks.

**Comment by chrisjenx** [comment]
Actually to follow up with what @jw said:
> why not a single, static `int[1]` that you mutate and re-use for each?

The whole inflation process is created on the MainThread, you can just set the `ATTR_ARR[0] = attributeId` every time.

**Pull request merged**
